# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='domain')),
                ('ip', models.CharField(max_length=255, verbose_name='IP')),
            ],
        ),
    ]
