# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=255, verbose_name='param')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
        ),
    ]
